name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: pdx1-shared-a1-34.dreamhost.com
          username: wagess
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/wagess/shop.stephanewagner.com
            git pull origin main
